apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    # Note this line will be overriden.
    app: replace-this
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080