apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  annotations:
    cloud-space: any
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
        port-num: "51462"
    spec:
      containers:
      - name: python
        image: python:latest
        command: ["python", "my-app", "--port", "$(PYTHON_PORT)"]
        ports:
        - containerPort: 51462
        env:
          - name: APP_LANG
            value: $(APP_LANG)