apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    # Note this line will be overriden.
    cloud-space: any
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8080
      - name: python
        image: python:latest
        ports:
        - containerPort: 50000