resources:
- deploy.yaml
- service.yaml

patches:
- target:
    kind: Deployment
  path: deploy-patch.yaml
- target:
    kind: Service
  patch: |-
    - op: replace
      path: /spec/selector/app
      value: nginx-cus