apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    # Should no-op when kustomized 
    cloud.resource.exception: true
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080